services:
  db:
    image: postgres:16-alpine
    container_name: lerniva-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lerniva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lerniva"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: lerniva-api
    restart: unless-stopped
    env_file:
      - apps/api/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lerniva
      JWT_SECRET: change-me-in-production
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 30d
      BUNNY_LIBRARY_ID: 612114
      BUNNY_API_KEY: 9ecd2bab-0318-4d1a-a2e667ee9cd9-647b-4f2b
      BUNNY_CDN_HOSTNAME: vz-d59a6d38-707.b-cdn.net
      BUNNY_WEBHOOK_SECRET: your-bunny-webhook-secret
      EMAIL_PROVIDER: resend
      RESEND_API_KEY: ${RESEND_API_KEY:-re_Msao34TS_BK2kuE6np2CqgHk2ZmWbTwi1}
      EMAIL_FROM: Lerniva <onboarding@resend.dev>
      EMAIL_VERIFICATION_REQUIRED: '${EMAIL_VERIFICATION_REQUIRED:-false}'
      EMAIL_VERIFICATION_TOKEN_HOURS: '24'
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000/api
        NEXT_PUBLIC_SITE_URL: http://localhost:3000
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_placeholder}
    container_name: lerniva-web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: production
      INTERNAL_API_URL: http://api:4000/api
    ports:
      - "3000:3000"

  adminer:
    image: adminer:4
    container_name: lerniva-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
