import pool from '../db/pool.js';

// GET /api/certificates/mine - Get all certificates for student
export async function getMyCertificates(req, res, next) {
  try {
    const studentId = req.user.id;

    const query = `
      SELECT cert.*,
        c.title as course_title,
        c.thumbnail as course_thumbnail,
        u.name as teacher_name
      FROM certificates cert
      JOIN courses c ON cert.course_id = c.id
      JOIN users u ON c.teacher_id = u.id
      WHERE cert.student_id = $1
      ORDER BY cert.issued_at DESC
    `;

    const result = await pool.query(query, [studentId]);

    res.json(result.rows);
  } catch (error) {
    next(error);
  }
}

// POST /api/certificates/generate/:courseId - Generate certificate
export async function generateCertificate(req, res, next) {
  try {
    const { courseId } = req.params;
    const studentId = req.user.id;

    // Check if student completed all lessons
    const completionQuery = `
      SELECT
        COUNT(l.id) as total_lessons,
        COUNT(CASE WHEN lp.completed THEN 1 END) as completed_lessons
      FROM lessons l
      LEFT JOIN lesson_progress lp ON l.id = lp.lesson_id AND lp.student_id = $2
      WHERE l.course_id = $1
    `;

    const completionResult = await pool.query(completionQuery, [courseId, studentId]);
    const { total_lessons, completed_lessons } = completionResult.rows[0];

    if (parseInt(total_lessons) === 0) {
      return res.status(400).json({ error: 'لا توجد دروس في هذه الدورة' });
    }

    if (parseInt(completed_lessons) < parseInt(total_lessons)) {
      return res.status(400).json({
        error: 'يجب إكمال جميع الدروس للحصول على الشهادة',
        progress: {
          completed: parseInt(completed_lessons),
          total: parseInt(total_lessons),
        },
      });
    }

    // Check if certificate already exists
    const existingCert = await pool.query(
      'SELECT * FROM certificates WHERE course_id = $1 AND student_id = $2',
      [courseId, studentId]
    );

    if (existingCert.rows.length > 0) {
      return res.json({
        ...existingCert.rows[0],
        message: 'الشهادة موجودة بالفعل',
      });
    }

    // Get course and student details
    const detailsQuery = `
      SELECT c.title as course_title, u.name as student_name
      FROM courses c, users u
      WHERE c.id = $1 AND u.id = $2
    `;

    const detailsResult = await pool.query(detailsQuery, [courseId, studentId]);
    const { course_title, student_name } = detailsResult.rows[0];

    // Create certificate (certificate_id is auto-generated by trigger)
    const insertQuery = `
      INSERT INTO certificates (student_id, course_id, student_name, course_title)
      VALUES ($1, $2, $3, $4)
      RETURNING *
    `;

    const result = await pool.query(insertQuery, [
      studentId,
      courseId,
      student_name,
      course_title,
    ]);

    res.status(201).json({
      ...result.rows[0],
      message: 'تهانينا! تم إصدار الشهادة بنجاح',
    });
  } catch (error) {
    next(error);
  }
}

// GET /api/certificates/verify/:certificateId - Verify certificate (public)
export async function verifyCertificate(req, res, next) {
  try {
    const { certificateId } = req.params;

    const query = `
      SELECT cert.*,
        c.title as course_title,
        u.name as student_name,
        t.name as teacher_name
      FROM certificates cert
      JOIN courses c ON cert.course_id = c.id
      JOIN users u ON cert.student_id = u.id
      JOIN users t ON c.teacher_id = t.id
      WHERE cert.certificate_id = $1
    `;

    const result = await pool.query(query, [certificateId]);

    if (result.rows.length === 0) {
      return res.status(404).json({
        valid: false,
        message: 'الشهادة غير موجودة',
      });
    }

    res.json({
      valid: true,
      certificate: result.rows[0],
    });
  } catch (error) {
    next(error);
  }
}
